### ISSUE TITLE
How do we use this?

### ISSUE THREAD

**Issue by shillshocked** [chipulaja/facebook-photo-albums-downloader#1]
I got my token, but how do I run the script?

**Comment by chipulaja** [comment]
please open file example.php,  change with your rule for example

$token       = "1234567890abcdefghijklmnopqrstuvwxyz";
$account   = "chipul.aja";

to run this program 
1. open your terminal console
2. go to directory
cd "/path/facebook-photo-albums-downloader-master" 
3. run the program
php example.php

![screenshot from 2016-06-22 10 25 50](https://cloud.githubusercontent.com/assets/3088220/16253808/d6f6651c-3863-11e6-909b-a8b50a9d8c9b.png)
